version: '3'

services:
  db:
    image: postgres:15.1-alpine3.17
    ports:
      - 54320:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=ray230899
      - POSTGRES_USER=ray
      - POSTGRES_DB=authjs-ntk
